language: elixir
sudo: false

elixir:
  - 1.7
otp_release:
  - 21.0

before_script:
  - mix local.hex --force
  - mix deps.get --only test

script:
  - mix test
  - mix credo

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report

after_success:
  - bash <(curl -s https://codecov.io/bash)